# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-View-TT-ForceUTF8
version:      0.03
version_from: lib/Catalyst/View/TT/ForceUTF8.pm
installdirs:  site
requires:
    Catalyst:                      5.5
    Catalyst::View::TT:            0.22
    Template::Provider::Encoding:  0.04

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.29
